### PR TITLE
Static version of openeffects.org via GitHub Pages

### PR DESCRIPTION
**Pull request by john-paulsmith**
This is a static version of the site with a GitHub Pages configuration. Once it's merged, we can turn on hosting and point the DNS to the GitHub url.

A preview is currently hosted at [https://openfx.borisfx.com](https://openfx.borisfx.com).

### CODE REVIEW

**Review by garyo — APPROVED** [review]
Looks great to me; thanks for doing this!

**Comment by garyo** [comment]
BTW, I can update the DNS records whenever this is ready.

**Comment by john-paulsmith** [comment]
@garyo I merged this and created a website branch to trigger the the automation, but get a message [Branch "website" is not allowed to deploy to github-pages due to environment protection rules.](https://github.com/AcademySoftwareFoundation/openfx/actions/runs/4205253753). I don't have access to the environment settings for the repo to configure this, can you look into it please?

**Comment by garyo** [comment]
OK, I enabled this. 
image

It says it is live at http://academysoftwarefoundation.github.io/openfx/ but that looks like the main README, so I think it needs to come from the `website/openeffects.org` subdir somehow.

**Comment by garyo** [comment]
Shoot - I just remembered we transferred the DNS to the Academy -- no longer at namecheap. I'll have to ask them to do that.
I see the IP addrs we need to set up:
```
To create A records, point your apex domain to the IP addresses for GitHub Pages.
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
To create AAAA records, point your apex domain to the IP addresses for GitHub Pages.
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8002::153
2606:50c0:8003::153
```

**Comment by garyo** [comment]
LFX support request sent: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/2/IT-25209

**Comment by garyo** [comment]
...and we are live! https://openeffects.org is now pointing to the static site. As an extra bonus, we now have an SSL cert.

**Pull request merged**
