### PR TITLE
Add section about private extension reverse domain naming

### PR DESCRIPTION
**Pull request by SonyDennisAdams**

### CODE REVIEW

**Review by garyo — APPROVED** [review]
LGTM! Thanks!

**Comment by garyo** [comment]
Could you re-push this with DCO signoff (`git commit ... -s`, so it adds the Signed-Off-By line at the end of the commit message)?

**Comment by SonyDennisAdams** [comment]
> Could you re-push this with DCO signoff (`git commit ... -s`, so it adds the Signed-Off-By line at the end of the commit message)?

Apparently not; the steps I tried did not work. So I'm creating another PR which you will receive shortly. I'll close this one without merging.

**Comment by SonyDennisAdams** [comment]
Closing; was missing DCO. Creating new PR fresh.

**Pull request closed without merging**
