### PR TITLE
Feature/prop bytes

### PR DESCRIPTION
**Pull request by fxtech**
This pull request adds the new Bytes property type to the ofxParam.h header, and adds sample code to the existing example for the Custom parameter type.
Feature Issue #145

### CODE REVIEW

**Review by revisionfx — COMMENTED** [review]
Happy to Approve - just a simple question.  
I forget how is the doc get updated so it's added to this list (pasted below)
There should maybe be a mention that this is exclusively assume constant step animation and the KF suite is used to find nearest ones if more than one... - also does an host expect the length to be constant for all frames (aside when null on a frame)? 

**By default the following parameter types animate…**

[kOfxParamTypeInteger](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeInteger)

[kOfxParamTypeInteger2D](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeInteger2D)

[kOfxParamTypeInteger3D](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeInteger3D)

[kOfxParamTypeDouble](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeDouble)

[kOfxParamTypeDouble2D](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeDouble2D)

[kOfxParamTypeDouble3D](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeDouble3D)

[kOfxParamTypeRGBA](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeRGBA)

[kOfxParamTypeRGB](https://openfx.readthedocs.io/en/main/Reference/DoxygenIndex.html#c.kOfxParamTypeRGB)

**Review by revisionfx — APPROVED** [review]

**Comment by fxtech** [comment]
I updated the custom example plugin code to correctly check for Bytes support and also added a test for correct handling of really large data (10MB).

**Review by garyo — APPROVED** [review]
Compiles OK for me. Looks good.

**Comment by garyo** [comment]
Ideally we should add C++ support, but this is good enough for the spec change.

**Pull request merged**
