### PR TITLE
Move OpenGL suite & CUDA/Metal/OpenCL into new ofxGPURender.h

### PR DESCRIPTION
**Pull request by garyo**
The new props should not have been in the main `ofxImageEffect.h`; moved them into the new file, along with the content of `ofxOpenGLRender.h` which now just includes the new `ofxGPURender.h`.

I also added `#pragma once` to some of the headers and fixed a missing `#include`. These should be done globally, IMHO.
Also improved the doc for some of the new props.

### CODE REVIEW

**Review by revisionfx — APPROVED** [review]
I have other requests to add after this, like a way to switch dynamically if we want gpu images or not... will add in a second round, not to make this contingent on other things. First step was having a generic GPU render header file.

**Review by revisionfx — APPROVED** [review]
I check with BMD, apparently the latest release includes our changes (their SDK dropped with app)...

**Comment by garyo** [comment]
Is there any reason to wait on merging this?

**Comment by Dithermaster** [comment]
It doesn't have the OpenCL image parts (combined header) just the BMD buffer part. If this can be added later, then OK to merge. If you want it included, then I need to add it.

**Comment by garyo** [comment]
Thanks for catching the missing OpenCL! It's probably simplest for me to merge this and then you can fix up OpenCL (rather than trying to patch my PR).

**Pull request merged**
