### PR TITLE
Gpu gain example

### PR DESCRIPTION
**Pull request by garyo**

### CODE REVIEW

**Comment by SonyDennisAdams** [comment]
The build folder structure for GPUGain does not match the other examples:
            build\Examples\GPUGain\Release\example-GPUGain.ofx.    <= different than the rest
            build\Examples\Release\example-Basic.ofx
            build\Examples\Release\example-Custom.ofx
            build\Examples\Release\example-DepthConverter.ofx
            build\Examples\Release\example-Invert.ofx
            build\Examples\Release\example-OpenGL.ofx
            build\Examples\Release\example-Rectangle.ofx
            build\Examples\Release\example-Test.ofx

**Comment by garyo** [comment]
GPUGain location should be fixed by c298169 (once it builds in CI)

**Comment by SonyDennisAdams** [comment]
@garyo 
OpenCL Buffer and Image support confirmed on Windows and Mac. The build option `OFX_SUPPORTS_OPENCLRENDER` is OFF by default, but needs to be ON for this example to work. Also, on Mac in Support/Plugins/CMakeLists.txt I had to add `"-framework OpenCL"` otherwise I got link errors against the OpenCL host API (e.g., `clBuildProgram`).

**Review by SonyDennisAdams — DISMISSED** [review]
I confirmed Windows and Mac OpenCL Buffer and Image support work

**Comment by revisionfx** [comment]
Another company just asked me why this is in Support but not in Examples folder?

Pierre

**Comment by garyo** [comment]
This example was created by Blackmagic, who generously donated it to us. It uses the C++ support lib. An example that doesn't use the support lib would be very welcome.

**Pull request merged**
